/*
 * This file was generated by the migration tool. Do not modify it manually.
 */

package com.mongodb.migration.kitchensink.domain.ports.incoming;

import com.mongodb.migration.kitchensink.domain.model.Member;
import java.util.List;
import java.util.Optional;

/** Incoming port for member service operations. */
public interface MemberService {
  Member registerMember(Member member) throws Exception;

  Optional<Member> findMemberById(String id);

  Optional<Member> findMemberByEmail(String email);

  List<Member> listAllMembers();

  void deleteMember(String id);
}
