/*
 * This file was generated by the migration tool. Do not modify it manually.
 */

package com.mongodb.migration.kitchensink.domain.ports.outgoing;

import com.mongodb.migration.kitchensink.domain.model.Member;
import java.util.List;
import java.util.Optional;

/** Outgoing port for member repository operations. */
public interface MemberRepository {
  Member save(Member member);

  Optional<Member> findById(String id);

  Optional<Member> findByEmail(String email);

  List<Member> findAllOrderedByName();

  void delete(String id);
}
